#!/bin/bash

# remove specified strings from the file generated by cdepscan (filesc.txt)

canrun=$(ls | grep -e '^filesc.txt$')
if [ -z $canrun ]; then
    printf "you have to run cdepscan before running this script\n"
    exit -2
fi

if [ -z "$1" ] || ([ "$1" == "-u" ] && [ $# -ne 1 ]); then
    printf "usage: ./rmstrcdeps [string1] [string2] ... or ./rmstrcdeps -u\n"
    exit -1
fi

# undo last remove
if [ "$1" == "-u" ]; then
    backup=$(cat filesc.txt.bak)
    printf "$backup" > filesc.txt
    rm filesc.txt.bak &> /dev/null
    printf "last remove operation undone\n"
    exit 0
fi

file=$(cat filesc.txt)

for string in $@; do
    sed -i.bak "/^$string$/d" ./filesc.txt
done

printf "removed $* from filesc.txt\n"